language: go

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - GO111MODULE=on
        - DOPPELGANGER_TEST_END_TO_END=full
        - DOPPELGANGER_TEST_SSH=true
    - os: linux
      env:
        - GO111MODULE=on
        - DOPPELGANGER_TEST_END_TO_END=full
        - DOPPELGANGER_TEST_SSH=true
        - DOPPELGANGER_TEST_DOCKER=true
        - DOPPELGANGER_TEST_DOCKER_BASE_IMAGE_NAME=alpine
        - DOPPELGANGER_TEST_DOCKER_IMAGE_NAME=doppelgangertest
        - DOPPELGANGER_TEST_DOCKER_CONTAINER_NAME=doppelgangertester

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

go:
  - "1.11.5"

install: true

before_script:
  - source scripts/setup_ssh.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source scripts/create_test_partitions_darwin.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source scripts/setup_docker.sh ; fi

script:
  - go version
  - go run scripts/build.go --mode=slim
  - go test -p 1 -v -coverpkg=./pkg/... -coverprofile=coverage.txt ./pkg/...
  - DOPPELGANGER_TEST_END_TO_END=slim go test -p 1 -race ./pkg/...
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GOARCH=386 go run scripts/build.go --mode=slim ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GOARCH=386 go test -p 1 ./pkg/... ; fi
  - bash <(curl -s https://codecov.io/bash)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then go run scripts/build.go --mode=release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go run scripts/build.go --mode=testing ; fi


after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source scripts/teardown_docker.sh ; fi

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/convert_windows_release_bundles.sh ; fi

deploy:
  provider: releases
  api_key:
    secure: oGoH8k4iqfXizSDUNaFRMqG+q0hYjJcPQBkCSlDWC/enMtn2HyT4UI+vRCksastjNS6ltGrwlebKVyOzkWQCvN/apiteDHgcwPvaJr4ioEZ/UdNobbD2sRyQ6mntXZoQLmTCouDpj47xQA/8bpWSsKNJscIrWuzBr1IUCnDWGPR27ninXX7eueIB9W2BCiuaXvRcvOmLOQslQ+sZEsUjZ2tJ1IB2gQiQdE0yIeHR3A6WsEKkkQWecCnNvuuhtAJZ0bcvR/aKGm3NPPzmvNHu05whvb55qpWjVBdxExatHNXFal4xvesgmFGzlbxkTOHl6QMauuVPJ0ctAEsWMjeNGYHVtmjR7d9+bpgMhpTtxFz6j/HEVs1hzLcsE96LUkxsK6Mc6xpOVI41rsTMLNYIPqjcfBa4/VNUEBFbX8J68BhJ9Ou3zV1f1N1b4nm6PO3asfVgCbYQNTg0Yx3/27KlNzymccui/LmR3l9jbNdQ/KaH689ZFi6+kTL1U8/i/cPo3rv1goQM0vSbuUe9zoydlfCmn5mnFH85PV2/oW55NrTDoHOD6OMUMAma7c48I4+unVSdg4k3IM+YE0uXHJ/OyPifNUXgp+TMQRb5LerMfjvf7HMyMnPjZZsV4COb55hsdH3dx6Yp8BIUxtRV1yzWlBzRo3DIZ5QqYNydc4Cirok=
  skip_cleanup: true
  file_glob: true
  file: build/release/doppelganger_*_*v*
  on:
    repo: RokyErickson/doppelganger
    condition: '"$TRAVIS_OS_NAME" == "osx"'
    tags: true




